spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/erupt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
    url: jdbc:mysql://120.79.215.51:3506/erupt?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: hbs # 改成线上环境的数据库连接用户名*
    password: mLwA$0%XEHuT # 改成线上环境的数据库连接密码*
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
