spring:
  profiles:
#    active: prod
    active: dev

server:
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true # 启用 gzip 压缩
  error:
    includeException: true
    includeStacktrace: ALWAYS
    includeMessage: ALWAYS