spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/erupt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  # 配置Redis缓存
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    # password: # Redis服务器连接密码（默认为空）
    timeout: 3000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 500 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    lettuce:
      shutdown-timeout: 0

erupt-app:
  verifyCodeCount: 2 # 登录失败几次，需要验证码
erupt:
  csrfInspect: true # 是否开启csrf防御
  redisSession: true # 是否开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置（同 spring boot）
  uploadPath: D:/erupt/attachment # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
  keepUploadFileName: false  # 是否保留上传文件原始名称
  upms:
    expire-time-by-login: 60 # 登录session时长（redisSession为true时有效）
  security:
    record-operate-log: true # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
